apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: source-secret-1
  namespace: test-source-ns
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  encryptedData:
    
  template:
    type: Opaque
    metadata:
      labels:
        "jenkins.io/credentials-type": usernamePassword
      annotations:
        "jenkins.io/credentials-description": credentials from Kubernetes